import { spawn } from "node:child_process"; import readline from "node:readline";
import pkg from "@xterm/headless"; const { Terminal } = pkg;
const env = Object.fromEntries(Object.entries(process.env).filter(([k]) => !k.startsWith("HERDR_")));
const t = new Terminal({ cols: 80, rows: 10, scrollback: 0, allowProposedApi: true });
const h = spawn("herdr", ["terminal","session","control",process.argv[2],"--cols","80","--rows","10"], { env });
readline.createInterface({ input: h.stdout }).on("line", l => { const m = JSON.parse(l); if (m.type === "terminal.frame") t.write(Buffer.from(m.bytes, "base64")); });
const send = o => h.stdin.write(JSON.stringify(o) + "\n");
const wait = ms => new Promise(r => setTimeout(r, ms));
const screen = () => new Promise(r => t.write("", () => { const s=[]; for (let y=0;y<10;y++) s.push(t.buffer.active.getLine(y).translateToString(true).trim()); r(s.filter(Boolean).join(" | ")); }));
const b64 = s => Buffer.from(s, "binary").toString("base64");
await wait(800);
send({ type: "terminal.input", text: "clear; for i in $(seq 1 200); do echo L$i; done\r" }); await wait(1500);
console.log("main, bottom:      ", await screen());
send({ type: "terminal.scroll", lines: 50, direction: "up" }); await wait(800);
console.log("main, scroll up 50:", await screen());
send({ type: "terminal.scroll", lines: 50, direction: "down" }); await wait(800);
send({ type: "terminal.input", text: "seq 1 200 | sed s/^/L/ | less --mouse +G\r" }); await wait(1500);
console.log("less, bottom:      ", await screen());
send({ type: "terminal.scroll", lines: 20, direction: "up" }); await wait(800);
console.log("less, herdr scroll:", await screen());
send({ type: "terminal.input", bytes: b64("\x1b[<64;5;5M".repeat(5)) }); await wait(800);
console.log("less, SGR wheel:   ", await screen());
send({ type: "terminal.input", bytes: b64("\x1b[5~") }); await wait(800);
console.log("less, PgUp:        ", await screen());
send({ type: "terminal.input", text: "q" }); h.stdin.end(); await wait(300); process.exit(0);
